---
abstract: 'add pod section from an interpolated piece of text.'
author:
  - 'Carnë Draug <cdraug@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-GenerateSection
requires:
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Moose::Autobox: 0
  MooseX::AttributeShortcuts: 0
  MooseX::Types::Moose: 0
  Pod::Weaver::Role::Section: 0
  namespace::autoclean: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/carandraug/pod-weaver-section-generatesection/issues
  homepage: https://github.com/carandraug/pod-weaver-section-generatesection
  repository: git://github.com/carandraug/pod-weaver-section-generatesection.git
version: 1.01
x_authority: cpan:CDRAUG
